"""Typeset cover_letter_TRS.md (generated by make_cover_letter.py) as a PDF letter for the submission system.
Handles the subset of Markdown the letter uses: paragraphs, **bold**, nested '-' bullets.
Usage: python make_cover_letter_pdf.py  ->  ../UPLOAD_TRS/INARCP_R22_Cover_Letter.pdf (pdflatex required)"""
import os, re, subprocess, shutil, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "cover_letter_TRS.md")
OUT = os.path.join(HERE, "..", "UPLOAD_TRS", "INARCP_R22_Cover_Letter.pdf")


def esc(t):
    t = t.replace("\\", r"\textbackslash{}")
    for a, b in (("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}")):
        t = t.replace(a, b)
    t = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", t)
    t = re.sub(r"10\^(-?\d+)", r"$10^{\1}$", t)
    t = t.replace("~", r"\textasciitilde{}").replace("Δ", r"$\Delta$").replace("κ", r"$\kappa$").replace("α", r"$\alpha$")
    t = re.sub(r"(https?://\S+?)([).,;]?)(\s|$)", lambda m: r"\url{" + m.group(1) + "}" + m.group(2) + m.group(3), t)
    return t


lines = open(SRC, encoding="utf8").read().splitlines()
body, depth = [], 0
for ln in lines:
    m = re.match(r"^(\s*)- (.*)$", ln)
    if m:
        lvl = len(m.group(1)) // 2 + 1
        while depth < lvl:
            body.append(r"\begin{itemize}[leftmargin=*,itemsep=1pt,topsep=2pt]"); depth += 1
        while depth > lvl:
            body.append(r"\end{itemize}"); depth -= 1
        body.append(r"\item " + esc(m.group(2)))
        continue
    while depth > 0:
        body.append(r"\end{itemize}"); depth -= 1
    body.append(esc(ln) if ln.strip() else "")
while depth > 0:
    body.append(r"\end{itemize}"); depth -= 1

tex = r"""\documentclass[11pt]{article}
\usepackage[T1]{fontenc}\usepackage[utf8]{inputenc}\usepackage{lmodern}
\usepackage[margin=2.3cm]{geometry}\usepackage{enumitem}\usepackage{xurl}\usepackage{hyperref}
\setlength{\parindent}{0pt}\setlength{\parskip}{6pt}\pagestyle{empty}
\begin{document}
\hfill 5 October 2026

""" + "\n".join(body) + "\n\\end{document}\n"
d = tempfile.mkdtemp()
open(os.path.join(d, "letter.tex"), "w", encoding="utf8").write(tex)
for _ in range(2):
    subprocess.run(["pdflatex", "--disable-installer", "-halt-on-error", "-interaction=nonstopmode", "letter.tex"], cwd=d, capture_output=True, check=True)
os.makedirs(os.path.dirname(OUT), exist_ok=True)
shutil.copy(os.path.join(d, "letter.pdf"), OUT)
print("written", OUT)
