"""R13 macros: a few derived numbers that the R13 text states, computed from saved R12 outcomes only.

Inputs : ../supplement/data/r12_summary.txt (Part L, pooled Pfa/alpha with 95% day-cluster intervals)
         ../manuscript/generated/r12_macros.tex (R12 macros generated by make_r12_tables.py)
Output : ../manuscript/generated/r13_macros.tex
No new experiment is run. Usage: python make_r13_macros.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SUMMARY = os.path.join(HERE, "..", "supplement", "data", "r12_summary.txt")
R12 = os.path.join(HERE, "..", "manuscript", "generated", "r12_macros.tex")
OUT = os.path.join(HERE, "..", "manuscript", "generated", "r13_macros.tex")

# Part L: "  alpha = 0.01" blocks of "stat  rule  ratio [lo, hi]  spread s"
L, alpha = {}, None
for line in open(SUMMARY, encoding="utf8"):
    if line.startswith("Part ") and not line.startswith("Part L"):
        if L:
            break
    m = re.match(r"\s+alpha = ([0-9.e-]+)", line)
    if m:
        alpha = float(m.group(1))
        continue
    m = re.match(r"\s+(\S+)\s+(conf|anal|boot)\s+([0-9.]+) \[([0-9.]+), ([0-9.]+)\]", line)
    if m and alpha is not None:
        L[(m.group(1), m.group(2), alpha)] = tuple(float(m.group(i)) for i in (3, 4, 5))

r12 = dict(re.findall(r"\\newcommand\{\\(\w+)\}\{([^}]*)\}", open(R12, encoding="utf8").read()))
M = {}

# Conformal ratios above one at 1e-2 (exchangeability check): one-bin P-ANMF
v = L[("P-ANMF(bin)", "conf", 0.01)]
M["PanmfBinConfTwo"], M["PanmfBinConfTwoLo"], M["PanmfBinConfTwoHi"] = (f"{x:.2f}" for x in v)
# IN-ARCP conformal at 1e-4 with interval
v = L[("IN1", "conf", 0.0001)]
M["InConfFour"], M["InConfFourLo"], M["InConfFourHi"] = (f"{x:.2f}" for x in v)

# IN-ARCP's CA law at 1e-4 with interval (the most robust model-based rule, still above design)
v = L[("IN1", "anal", 0.0001)]
M["InAnalFourLo"], M["InAnalFourHi"] = (f"{x:.2f}" for x in v[1:])

# Model-based laws of the whitened statistics at 1e-4 (the set used for LAnalMin/MaxFour, plus IN1's CA law)
whitened = ["IN1", "IN4", "OS1_8", "NA4", "D-IN4", "PAMF-H(w)", "P-ANMF(bin)", "P-ANMF", "ANMF-SCM(w)", "ANMF-FP(w)", "Clip-OS1"]
anal4 = {k: L[(k, "anal", 0.0001)][0] for k in whitened}
over = [k for k, x in anal4.items() if x > 2.0]
assert len(whitened) - len(over) == 1 and "IN1" not in over, anal4  # only IN-ARCP's CA law within twofold
M["NWhitenedLaws"] = str(len(whitened))
M["NWhitenedLawsFail"] = str(len(over))

# 77 GHz certificate cost (dB): certified clipped vs clipped with a clean threshold
M["JCertCostClean"] = f"{float(r12['JCertScrCclean']) - float(r12['JClipScrCclean']):.1f}"
M["JCertCostAll"] = f"{float(r12['JCertScrC']) - float(r12['JClipScrC']):.1f}"

with open(OUT, "w", encoding="utf8") as f:
    f.write("% Generated by analysis_provenance/make_r13_macros.py from saved R12 outcomes. Do not edit.\n")
    for k, x in M.items():
        f.write(f"\\newcommand{{\\{k}}}{{{x}}}\n")
print(open(OUT, encoding="utf8").read())
