"""R11 macros from research/r7c/r11/r11_summary.json -> ../manuscript/generated/r11_macros.tex."""
import os, json
import numpy as np
from scipy.optimize import brentq
HERE = os.path.dirname(os.path.abspath(__file__))
s = json.load(open(os.path.join(HERE, "..", "..", "02_paper_repo_inarcp", "research", "r7c", "r11", "r11_summary.json")))
f1 = lambda x: f"{x:.1f}"; f2 = lambda x: f"{x:.2f}"; f3 = lambda x: f"{x:.3f}"; M = {}
m = 16; law = lambda T, k: np.prod([(m - i) / (m - i + T) for i in range(k)])
Tca = m * (0.01 ** (-1 / m) - 1); ca = brentq(lambda x: (1 + Tca / (m * (1 + x))) ** (-m) - 0.5, 1e-3, 1e4)
for k, nm in ((8, "Eight"), (12, "Twelve")):
    T = brentq(lambda t: law(t, k) - 0.01, 1e-3, 1e5); M[f"OSLoss{nm}"] = f2(10 * np.log10(brentq(lambda x: law(T / (1 + x), k) - 0.5, 1e-3, 1e5) / ca))
o8 = s["O3|OS1_8"]; M["OsPersFirst"], M["OsPersLast"] = f3(min(o8)), f3(max(o8))
M["InPersLast"] = f3(s["O3|IN1"][7]); M["OsTwelveLookFour"] = f3(s["O3|OS1_12"][4]); M["OsTwelveLookFive"] = f3(s["O3|OS1_12"][5])
M["OsCostEight"] = f1(s["O2|OS1_8"][1]); M["OsCostTwelve"] = f1(s["O2|OS1_12"][1])
M["OsSpreadEight"] = f2(s["O1|OS1_8"]["spread"]); M["OsSpreadTwelve"] = f2(s["O1|OS1_12"]["spread"])
M["OsLawEight"] = f3(s["O7|OS1_8|0.1"][0]); M["OsLawTwelve"] = f3(s["O7|OS1_12|0.1"][0])
M["OsRampGain"] = f1(s["O4gain"][0]); M["OsDwellWorse"] = f1(s["O5|OS1_8sum-IN1sum|0.5"][0])
M["JkMaskIN"] = f1(s["J|N|A|IN1"]["scr50"][3]); M["JkCleanIN"] = f1(s["J|N|A|IN1"]["scr50"][0])
M["JkNoZero"] = f1(s["Jall|N|A|IN1"]); M["JkZero"] = f1(s["Jall|Z|A|IN1"])
pf = [x for run in ("A", "C") for x, n in zip(s[f"J|Z|{run}|IN1"]["pfa"], s[f"J|Z|{run}|IN1"]["n"]) if n >= 500]
M["JkPfaLo"], M["JkPfaHi"] = f"{min(pf):.4f}", f"{max(pf):.4f}"
out = os.path.join(HERE, "..", "manuscript", "generated", "r11_macros.tex")
open(out, "w").write("% Generated by analysis_provenance/make_r11_macros.py from the saved R11 outcomes. Do not edit.\n" + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in sorted(M.items())))
print(open(out).read())
