"""R17 outputs for the manuscript: macros (generated/r17_macros.tex), the supplement section (supplement/sec_r17.tex)
and its verbatim output (supplement/data/r17_summary.txt), from the saved outcomes in the code repository:
research/r7c/study/results/r17/r17_outcomes.json and r17_summary.txt (run_r17_jku.py, protocol r17/PROTOCOL_R17.md).
No new experiment is run. Usage: python make_r17_outputs.py"""
import json, os, hashlib
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..", "02_paper_repo_inarcp", "research", "r7c")
if not os.path.isdir(REPO):
    REPO = r"C:\Users\DELL\Downloads\MS thess\02_paper_repo_inarcp\research\r7c"
RES = os.path.join(REPO, "study", "results", "r17")
MAN, SUP = os.path.join(HERE, "..", "manuscript"), os.path.join(HERE, "..", "supplement")

jp = os.path.join(RES, "r17_outcomes.json")
want = open(jp + ".sha256").read().split()[0]
assert hashlib.sha256(open(jp, "rb").read().replace(b"\r\n", b"\n")).hexdigest() == want, "outcome file changed"
O = json.load(open(jp))
DETS = ("IN1", "CA-CM", "OS-CM", "Range-CA")
BIN0, BLOCK, M = 8, 5, 16

ev = np.array(O["events_prim"]).reshape(-1, 2)
nblk = len(np.unique((ev[:, 1] - M) // BLOCK))
pf = [O[f"Z|pfa|{d}|0.01"] / 0.01 for d in DETS]
pd = {d: np.array(O[f"Z|pd3|prim|{d}|0.01"]) for d in DETS}
snr = np.array([np.nan if s is None else s for s in O["Z|snr_prim"]], float)
ok = np.isfinite(snr); med = np.median(snr[ok]); hi = ok & (snr > med); lo = ok & (snr <= med)
dif = pd["IN1"] - pd["CA-CM"]
assert nblk < 8, "E1 status changed: revise the descriptive wording"
bs = np.sort(ev[:, 0]); cut = bs[np.argmax(np.diff(bs))]                     # largest gap splits direct / bistatic
n_dir, n_bis = int((ev[:, 0] <= cut).sum()), int((ev[:, 0] > cut).sum())
pk = np.array(O["peaks"]); both = (pk[:, 0] >= 0) & (pk[:, 1] >= 0)
sep = float(np.median(np.abs(pk[both, 0] - pk[both, 1])))
n_frames = int(ev[:, 1].max() - ev[:, 1].min() + 1)

M_ = {
    "PedEvents": str(len(ev)), "PedBlocks": str(nblk), "PedBlocksReq": "eight",
    "PedRangeLo": f"{(ev[:, 0].min() + BIN0) * 0.15:.1f}", "PedRangeHi": f"{(ev[:, 0].max() + BIN0) * 0.15:.0f}",
    "PedPfaMin": f"{min(pf):.2f}", "PedPfaMax": f"{max(pf):.2f}",
    "PedIN": f"{pd['IN1'].mean():.2f}", "PedCA": f"{pd['CA-CM'].mean():.2f}",
    "PedOS": f"{pd['OS-CM'].mean():.2f}", "PedRCA": f"{pd['Range-CA'].mean():.2f}",
    "PedR": f"{O['Z|r_abs_median']:.2f}",
    "PedHigh": f"{dif[hi].mean():.2f}", "PedLow": f"{dif[lo].mean():.2f}",
}
with open(os.path.join(MAN, "generated", "r17_macros.tex"), "w", encoding="utf8") as f:
    f.write("% Generated by analysis_provenance/make_r17_outputs.py from saved R17 outcomes. Do not edit.\n")
    for k, v in M_.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

os.makedirs(os.path.join(SUP, "data"), exist_ok=True)
import textwrap
NL = chr(10)
with open(os.path.join(SUP, "data", "r17_summary.txt"), "w", encoding="utf8", newline=NL) as f:   # long lines wrapped
    for line in open(os.path.join(RES, "r17_summary.txt"), encoding="utf8").read().splitlines():
        ind = len(line) - len(line.lstrip())
        f.write(NL.join(textwrap.wrap(line, 160, subsequent_indent=" " * (ind + 4), drop_whitespace=False)) + NL)
sec = r"""\section{Real onsets of a walking person at 77~GHz (R17)}\label{sup:r17}
Frozen protocol \texttt{r17/PROTOCOL\_R17.md}, committed and pushed before the data were obtained; verdicts in \texttt{r17/RESULTS\_R17.md}. In the pedestrian run of the 77~GHz data (\texttt{meas\_3\_int\_A\_pedestrian}, interference scenario A) a person walks in front of Station 1. Frames are 200~ms apart, so the person moves through the 15-cm range bins between frames, and each arrival of its return in a bin is a real onset in that bin's frame-to-frame sequence. Because the receivers are real-valued, Station 1 sees the person twice: directly, and bistatically via Station 2's transmission, about SEPB bins (SEPM~m) farther in this run. The NEV onsets are those of both returns (NDIR direct, NBIS bistatic) in adjacent bins over NFR frames, so they are not independent arrivals.

\emph{Ground truth.} Station 1's range-Doppler map over all 128 chirps and 16 receivers (fast-time zeroing). A bin is moving in a frame when its largest power over Doppler bins at least two from zero exceeds its median over the 100 frames by 10~dB. An onset is a bin that becomes moving after 16 frames without moving energy; it is the person's when one of the frame's two strongest moving peaks (13~dB) lies within three bins in the onset frame or the next two.

\emph{Detectors.} One chirp per frame (chirps 0, 32, 64, 96; receivers 0, 5, 10, 15: 16 looks), history of 16 frames: IN-ARCP (AR(1) per bin, fitted on clean frame pairs), the power clutter map (CA-CM: power over the mean history power), its OS form (OS-CM: eighth smallest of 16) and range CA-CFAR on the current frame (2 guard and 8 reference bins on each side). Conformal thresholds from null episodes of even bins, false alarms on odd bins. The primary endpoint is detection within three frames of the onset.

\emph{Outcome.} The protocol required onsets in at least eight distinct five-frame blocks; the person was tracked for about six seconds and the onsets fall in seven, so expectation E1 is not met and every result is descriptive. Descriptively, all lie on the side the protocol expected: false-alarm rates at design, IN-ARCP $\ge$ CA-CM $>$ OS-CM $>$ range CA-CFAR, and IN-ARCP's edge over CA-CM confined to the half of the onsets in bins with stronger static returns, as Proposition~\ref{M-prop:gain} predicts for nearly uncorrelated frame-to-frame clutter. \emph{Limitations} (stated as the protocol requires): one walk, tracked for about six seconds, by one person; ground clutter at 77~GHz, not sea clutter; frame-rate rather than pulse-rate slow time; ground truth from the same radar's range-Doppler processing, with no external sensor. Before the expectations were written, a mechanics check ran the whole chain on the interference run without the pedestrian, with a synthetic walker; its output, including the four detectors' detection rates for that walker, is \texttt{r17/MECHANICS\_R17.txt}. The onset rule, the three-frame endpoint and the expectations were set after this check, and the AR(1) coefficient is fitted on the same file as the test.

Output of \texttt{run\_r17\_jku.py}, long lines wrapped (intervals are understated with seven blocks):
\dataverb{r17_summary}
"""
sec = (sec.replace("SEPB", f"{sep:.0f}").replace("SEPM", f"{sep * 0.15:.0f}").replace("NEV", str(len(ev)))
       .replace("NDIR", str(n_dir)).replace("NBIS", str(n_bis)).replace("NFR", str(n_frames)))
open(os.path.join(SUP, "sec_r17.tex"), "w", encoding="utf8", newline="\n").write(sec)
print("\n".join(f"{k} = {v}" for k, v in M_.items()))
