"""Verification macros: the Monte Carlo agreement that the Introduction states for the laws of Section IV.

Inputs : ../supplement/data/verify_laws_output.txt (r12/verify_laws.py; its own summary line)
         ../supplement/data/theory_check_independent_output.txt (r14/theory_check_independent.py)
Output : ../manuscript/generated/verification_macros.tex
No new experiment is run. Usage: python make_verification_macros.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "supplement", "data")
OUT = os.path.join(HERE, "..", "manuscript", "generated", "verification_macros.tex")

# r12 summary line: "Summary: 65 probability checks, max |z| = 2.91, 0 with |z| > 3; ..."
txt = open(os.path.join(DATA, "verify_laws_output.txt"), encoding="utf8").read()
m = re.search(r"Summary: (\d+) probability checks, max \|z\| = ([0-9.]+), (\d+) with \|z\| > 3", txt)
n_checks, max_z, n_over3 = int(m.group(1)), m.group(2), int(m.group(3))
assert n_over3 == 0, "the text states that every check lies within 3 standard errors; recheck the wording"

# The independent re-implementation must report every check passed, with no BAD line.
ind = open(os.path.join(DATA, "theory_check_independent_output.txt"), encoding="utf8").read()
assert "ALL CHECKS PASSED" in ind and not re.search(r"^BAD", ind, re.M), "independent re-check did not pass"

# The printed maximum is rounded (2.91 is 2.9125 in r12/verify_laws.json), so the text states the bound
# that the script's own count guarantees: no check beyond 3 standard errors.
M = {"NLawChecks": str(n_checks), "LawChecksZBound": "3"}
with open(OUT, "w", encoding="utf8") as f:
    f.write("% Generated by analysis_provenance/make_verification_macros.py from saved Monte Carlo outputs. Do not edit.\n")
    for k, v in M.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print(open(OUT, encoding="utf8").read())
