"""Generate supplement/sec_r18.tex for the R18 senior-review round.

Three derived subsections and one relocated one:
  S1  the operating regime of the per-look screen (finding F2, in full)
  S2  pivotality across clutter power, all thirteen statistics, both threshold rules (F3, F4)
  S3  the cost of a cell-wise detector (F7)
  S4  the pulse-blanking thresholds, moved out of the main text to buy space (C19)

S2 is parsed from supplement/data/r12_summary.txt. S1, S3 and S4 are arithmetic on, or
restatements of, quantities already stated in the manuscript. No radar sample is read here,
so no new empirical outcome is computed and CLAUDE.md rule 5 does not apply.

Placeholders are @@TOKEN@@ rather than %-formatting, because the template is LaTeX and full
of literal per-cent signs.

Run from 03_submission_IEEE-TRS/:   python analysis_provenance/make_r18_supp.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DATA = os.path.join(PKG, "supplement", "data")
OUT = os.path.join(PKG, "supplement", "sec_r18.tex")

# ----------------------------------------------------------------- parse Part L of r12_summary
PARTL = re.compile(
    r"^\s{4}(?P<stat>\S+)\s+(?P<rule>conf|anal|boot)\s+"
    r"(?P<ratio>[\d.]+)\s+\[[^\]]*\]\s+spread\s+(?P<spread>[\d.]+)\s*$"
)
partL, alpha, in_partL = {}, None, False
for line in open(os.path.join(DATA, "r12_summary.txt"), encoding="utf-8"):
    if line.startswith("Part L"):
        in_partL = True
        continue
    if in_partL and line.startswith("Part "):
        break
    if not in_partL:
        continue
    m = re.match(r"\s{2}alpha = (\S+)", line)
    if m:
        alpha = float(m.group(1))
        continue
    m = PARTL.match(line.rstrip("\n"))
    if m:
        partL[(m.group("stat"), m.group("rule"), alpha)] = (
            float(m.group("ratio")), float(m.group("spread")))

# the thirteen statistics of Table I, in its order, with their manuscript names
ROWS = [
    ("IN1", "IN-ARCP (CA law)"),
    ("IN4", "IN-AR(4) (CA law)"),
    ("OS1_8", "OS scale, $k=8$ (OS law)"),
    ("NA4", "NA-AR(4) (Gaussian)"),
    ("CA16", "Power, CA (white law)"),
    ("OSraw", "Power, OS (white law)"),
    ("D-IN4", "Integration (dwell law)"),
    ("PAMF-H(w)", "PAMF-H, one Doppler (CA law)"),
    ("P-ANMF(bin)", "P-ANMF, one bin (Beta)"),
    ("P-ANMF", "P-ANMF, max (Fisher's $g$)"),
    ("ANMF-SCM(w)", "ANMF-SCM (Kraut--Scharf)"),
    ("ANMF-FP(w)", "ANMF-Tyler (FP law)"),
    ("Clip-OS1", "Clipped, OS scale (Gaussian sim.)"),
]
ALPHAS = (1e-2, 1e-3, 1e-4)


def cell(stat, rule, a):
    v = partL.get((stat, rule, a))
    if v is None:
        return "---"
    s = v[1]
    if s >= 1e4:
        return "$>10^{4}$"
    return f"{s:.1f}" if s < 10 else f"{s:.0f}"


# ----------------------------------------------------------------- S1 arithmetic
# R18.2: l* is Doppler- AND radar-dependent, so it is evaluated at each radar's own
# measured |r|. A single value (IPIX's |rho| = 0.93) had been used for all three rows.
M_OVER_QSQ = 2.998   # m/q^2 at m = 16 and Pfa = 1e-2 (Section III-D of the manuscript)


def l_star_opposite(abs_r):
    """Corollary 4 at the opposite Doppler, where |d|^2 = (1 + |r|)^2."""
    return 1.0 + M_OVER_QSQ - 1.0 / (1.0 + abs_r) ** 2


R_IPIX, R_NETRAD, R_JKU = 0.96, 0.975, 0.12
L_STAR_OPP = l_star_opposite(R_IPIX)
DELTA = 8            # guard length used throughout
PRF_HZ = 1000.0      # IPIX and NetRAD pulse repetition frequency
FRAME_S = 0.200      # JKU 77 GHz frame interval
CELL_M = 15.0        # IPIX range-cell width
M_HIST = 16
P_AR = 1
LAMBDA_X = 0.032     # m, X-band carrier wavelength of the IPIX class of radar

horiz = DELTA + L_STAR_OPP                      # IPIX, and NetRAD to the printed digit
horiz_netrad = DELTA + l_star_opposite(R_NETRAD)
horiz_jku = DELTA + l_star_opposite(R_JKU)
v_unamb = LAMBDA_X * PRF_HZ / 4.0
SPEEDS = (5.0, 10.0, 30.0, 100.0, 300.0)

speed_rows = []
for v in SPEEDS:
    looks = CELL_M * PRF_HZ / v
    looks_s = f"{looks:,.0f}".replace(",", "{,}")
    speed_rows.append(f"{v:.0f} & {looks_s} & {100.0 * horiz / looks:.2f}\\%\\\\")

# ----------------------------------------------------------------- S3 arithmetic
# R18.1: the saved search gives 31,477 at alpha = 1e-4 (r12/calibration_size.txt); an
# episode spans m + Delta + 1 pulses with design rule 1's guard; and the clutter cells are
# 7 to 9 per IPIX file, not 14 (research/r7c/ipix.py, load(keep='clutter')).
cal_eps = 31477
EP_SPAN = M_HIST + DELTA + 1
N_CELLS_MIN, N_CELLS_MAX = 7, 9
cal_sec_max = cal_eps * EP_SPAN / N_CELLS_MIN / PRF_HZ
cal_sec_min = cal_eps * EP_SPAN / N_CELLS_MAX / PRF_HZ
state = M_HIST + DELTA + P_AR

TPL = r"""% Generated by analysis_provenance/make_r18_supp.py. Do not edit.
\section{Operating regime, pivotality and cost (R18)}\label{sup:r18}
Added in the R18 senior-review round. It computes no new outcome: every row is either parsed
from the frozen summaries above or arithmetic on quantities stated in the paper. Equation and
result numbers without the prefix S refer to the paper.

\subsection{The operating regime of the per-look screen}\label{sup:regime}
Corollary~\ref{M-cor:horizon} gives the visibility horizon in \emph{looks}. What that means in
practice depends on how long a look lasts, and the paper's three radars set that three orders
of magnitude apart. At $m=16$ and $P_{\rm fa}=10^{-2}$ the horizon is
@@LSTAR@@ looks at the opposite Doppler on IPIX and negative at the clutter Doppler, so with
the $\Delta=@@DELTA@@$ guard a strong persistent target is kept for at most
$\Delta+\ell^{\ast}=@@HORIZ@@$ looks there. Because $\ell^{\ast}$ depends on $|r|$, each
row below uses that radar's own measured value:

\begin{center}\small
\begin{tabular}{llll}
\toprule
Radar & Look interval & Guarded horizon & Measured $|r|$ at that lag\\
\midrule
IPIX, X-band & 1~ms (1~kHz) & @@HORIZMS@@~ms & 0.96 (median over units)\\
NetRAD, S-band & 1~ms (1~kHz) & @@HORIZMSNET@@~ms & 0.97--0.98 (at or near the clamp)\\
JKU, 77~GHz & 200~ms (frame) & @@HORIZS@@~s & 0.12 (median over bins)\\
\bottomrule
\end{tabular}
\end{center}

\noindent Correlation and target emergence jointly constrain the look interval.

\emph{Short enough that the clutter is still correlated.} The whitening gain is the clutter
attenuation of the one-step predictor (Proposition~\ref{M-prop:gain}), so it follows $|r|$ at
the look lag. At 1~kHz on both sea-clutter radars $|r|$ is near one, and against the same
comparator --- the raw-power OS detector at the first look --- the measured gain is 10.62~dB
[7.05, 12.69] on IPIX and censored at $\ge$12.2~dB on NetRAD, where IN-ARCP already reached
$P_{\rm d}=0.5$ at the lowest SCR tested. The two are not separable. Between 77~GHz frames
$|r|$ is 0.12 and the measured gain is nil: IN-ARCP detects 0.30 of the pedestrian onsets
against 0.27 for a power clutter map, a difference of 0.03 on 74 onsets falling in seven
blocks, which is descriptive and not a difference. Proposition~\ref{M-prop:gain} predicted
that parity in the frozen R17 protocol, written before the pedestrian file was downloaded,
although the frame-to-frame correlation behind the prediction had been measured on a companion
recording of the same scenario. It is consistent with the gain being the predictor's clutter
attenuation; the pre-specified and met IPIX comparison above is the stronger evidence.

\emph{Target emergence must outpace scale contamination.} Range-cell residence is the cell width divided by radial speed, but crossing a bin boundary does not create a guaranteed abrupt onset. A point target's range response moves continuously across bins; its sidelobes and main-lobe entry can contaminate the next bin's history before the peak arrives. The ramp experiments show why this matters. The following arithmetic assumes an ideal abrupt onset into each clean bin at the most favorable Doppler. It gives a horizon fraction, not a measured detection duty:

\begin{center}\small
\begin{tabular}{lll}
\toprule
Radial speed (m/s) & Looks in one cell & Ideal horizon fraction\\
\midrule
@@SPEEDROWS@@
\bottomrule
\end{tabular}
\end{center}

\noindent The ideal horizon fraction is $\Delta+\ell^{\ast}$ divided by the looks in a cell. Two
caveats keep the right-hand column from being read as a specification. First, at 1~kHz the
unambiguous radial-speed interval at X-band ($\lambda\approx@@LAMBDA@@$~m) is about
$\pm@@VUNAMB@@$~m/s, so the faster rows fold in Doppler, and the detector does not control
whether the folded Doppler avoids the clutter line. Second, $\ell^{\ast}$ is itself
Doppler-dependent and the table uses its opposite-Doppler value, which is the best case.

The design consequence is the one stated in design rule 1 of the paper: measure $|r|$ at the
intended look interval before choosing it, and read the horizon in the time units of that
interval. A staring radar at 1~kHz sits at one extreme, where the gain is large and onsets are
rare. A scan-to-scan clutter map sits at the other, where a new return can have a longer horizon but the
correlation gain may be lost. The paper's evidence covers neither the middle nor any operational scan pattern,
so no intermediate look rate can yet be recommended. Real target range responses and
clutter correlation must be measured together at the proposed lag.

\subsection{Pivotality across clutter power, all thirteen statistics}\label{sup:pivot}
Table~\ref{tab:pivot} gives the texture-quintile spread, the ratio of the largest to the
smallest measured false-alarm rate over quintiles of local clutter power, for every statistic
of Table~\ref{M-tab:lowpfa} under both threshold rules. The spread is a pre-specified outcome
of the frozen protocol; the two readings of it below are exploratory.

\emph{The remedy recommended for persistent targets has a strongly texture-dependent rate.}
Proposition~\ref{M-prop:blind} rules out history normalization for a target present throughout
the history, and the paper recommends the self-normalized whitened Doppler statistic instead.
Its conformal rate is compliant when pooled (1.04 at $10^{-2}$, 1.47 at $10^{-4}$) but varies
by a factor of @@PANMF4@@ across texture quintiles at $10^{-4}$, against @@IN4SPREAD@@ for
IN-ARCP. It carries the widest spread in the table at $10^{-2}$, though not at the two lower
design rates, where the saturating clipped integrator is wider still. The statistic is scale-invariant and therefore texture-pivotal in pure
compound-Gaussian clutter. Additive noise can break this invariance
(Corollary~\ref{M-cor:texture}); residual correlation and model mismatch can also contribute.
The quintile spreads do not isolate the cause. The dwell stays in one range cell.

\emph{The model-based laws fail in two distinct ways.} Among the rules that exceed twice design
at $10^{-4}$, the order-statistic and maximum-DFT laws carry the largest texture spreads
(@@OS3@@ and @@FISH3@@ at $10^{-3}$, against @@IN3@@ for the CA law of IN-ARCP), so their
rate depends strongly on clutter power. The summary prints only the max/min ratio, but the saved outcome arrays retain all five
quintile exceedance counts and denominators. No direction or cause follows from a spread
alone. Three other rules behave differently:
the clipped integrator's simulated threshold fails worse still in the pooled rate (17.19 at
$10^{-3}$, 59.89 at $10^{-4}$) and the two ANMF laws less badly (3.57 and 2.66 at $10^{-3}$),
but all three almost evenly across quintiles (@@CLIP3@@, @@SCM3@@ and @@FP3@@). For the
Kraut--Scharf law that is expected, since the paper's simulation shows it already failing
2.8--3.4-fold at $10^{-2}$ in compound-Gaussian clutter, where the real failure is smaller.
Attributing the difference to tail weight would require an analysis beyond these spread
summaries; it is not established here.

\begin{table}[h]
\centering\small
\caption{Texture-quintile spread of the measured false-alarm rate (max/min over quintiles of
local clutter power, $\pm1024$-pulse proxy), IPIX, 56 units, from \texttt{r12/analyze\_r12.py}
Part L. Conformal: split-conformal threshold. Model: the rule named in
Table~\ref{M-tab:lowpfa}. The clipped integrator's conformal spread at $10^{-4}$ is unbounded
because some quintiles record no false alarm at all, its statistic having saturated.}
\label{tab:pivot}
\begin{tabular}{lcccccc}
\toprule
 & \multicolumn{3}{c}{Conformal} & \multicolumn{3}{c}{Model-based rule}\\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
$\alpha$ & $10^{-2}$ & $10^{-3}$ & $10^{-4}$ & $10^{-2}$ & $10^{-3}$ & $10^{-4}$\\
\midrule
@@PIVOTROWS@@
\bottomrule
\end{tabular}
\end{table}

\subsection{What a cell-wise detector costs}\label{sup:cost}
The paper puts the detector where a range CFAR stage would go, so that is the comparison a
system designer needs.

\emph{Arithmetic.} Per range cell and per pulse: $p$ complex multiply--accumulates for the
AR($p$) innovation, one magnitude-squared, one add and one subtract to slide the scale window,
one division and one comparison. That is $O(p)$ complex and $O(1)$ real operations, the same
order as a sliding-window range CFAR, and the reference-window sum also admits a constant-cost sliding update.

\emph{State.} $m+\Delta+p=@@STATE@@$ complex samples per range cell, for $m=16$, $\Delta=8$ and
AR(1). A range CFAR needs no per-cell slow-time state at all; a clutter map needs one level per
cell. This is the real cost of the construction, and it scales with the number of cells.

\emph{Threshold storage.} One scalar per statistic. Because innovation normalization makes the
score close to pivotal --- in one analysis at $10^{-2}$, texture-quintile spread 1.7 against
87.5 for the unnormalized statistic and 9.8 for normalization by the raw history RMS --- one
threshold can serve every range cell, and a cell's level need not be learned or stored. That is
the operational payoff of the pivotality result. It is only approximate: the same spread is 2.7
at $10^{-4}$ on IPIX and 2.40 on NetRAD, so one shared threshold does not hold the per-cell
rate exactly at the rates the paper cares about.

\emph{Clean data for calibration.} Section~\ref{M-sec:calib} gives
$\PP\{P_{\rm fa}>2\alpha\}\le0.05$ for i.i.d.\ continuous scores and every $n$ beyond about $3.15/\alpha$. At
$\alpha=10^{-4}$ that is @@CALEPS@@ episodes. An episode spans $m+\Delta+1=@@EPSPAN@@$ pulses
once design rule 1's guard is in place, and the clutter cells are the 14 range cells less the
target cells and one guard cell on each side, which is @@CELLSMIN@@ to @@CELLSMAX@@ per IPIX
file, not 14. Drawn as non-overlapping episodes and pooled over those cells, it is
@@CALSECMIN@@ to @@CALSECMAX@@~s of clean recording at 1~kHz. This is an i.i.d.\ planning
calculation, not a guarantee for temporally or spatially dependent episodes. Non-overlap does
not ensure independence; drift and dependence require separate validation when the regime changes.

\subsection{Pulse blanking: the thresholds}\label{sup:blank}
Moved here from Section~\ref{M-sec:model} of the paper. Pulse blanking discards an innovation
power, and the innovation after it, when the power exceeds both ten times the history median
and four times a robust level of its block. That level is the history median for history terms
and the third-smallest dwell power for dwell terms. The remaining dwell powers are integrated.
Blanking is calibrated on clean episodes blanked at hit positions drawn from the hit model, so
it has a conformal threshold but no certificate: nothing bounds the statistic when a hit
survives the blanking rule.
"""

SUBS = dict(
    LSTAR=f"{L_STAR_OPP:.1f}",
    DELTA=str(DELTA),
    HORIZ=f"{horiz:.1f}",
    HORIZMS=f"{1000.0 * horiz / PRF_HZ:.0f}",
    HORIZMSNET=f"{1000.0 * horiz_netrad / PRF_HZ:.0f}",
    HORIZS=f"{horiz_jku * FRAME_S:.1f}",
    SPEEDROWS="\n".join(speed_rows),
    LAMBDA=f"{LAMBDA_X:.3f}",
    VUNAMB=f"{v_unamb:.0f}",
    PANMF4=cell("P-ANMF", "conf", 1e-4),
    IN4SPREAD=cell("IN1", "conf", 1e-4),
    OS3=cell("OS1_8", "anal", 1e-3),
    FISH3=cell("P-ANMF", "anal", 1e-3),
    IN3=cell("IN1", "anal", 1e-3),
    CLIP3=cell("Clip-OS1", "anal", 1e-3),
    SCM3=cell("ANMF-SCM(w)", "anal", 1e-3),
    FP3=cell("ANMF-FP(w)", "anal", 1e-3),
    PIVOTROWS="\n".join(
        name + " & " + " & ".join(
            [cell(stat, "conf", a) for a in ALPHAS]
            + [cell(stat, "anal", a) for a in ALPHAS]
        ) + r"\\"
        for stat, name in ROWS
    ),
    STATE=str(state),
    CALEPS=f"{cal_eps:,.0f}".replace(",", "{,}"),
    MP1=str(M_HIST + 1),
    CALSECMIN=f"{cal_sec_min:.0f}",
    CALSECMAX=f"{cal_sec_max:.0f}",
    EPSPAN=str(EP_SPAN),
    CELLSMIN=str(N_CELLS_MIN),
    CELLSMAX=str(N_CELLS_MAX),
)

TEX = TPL
for _k, _v in SUBS.items():
    TEX = TEX.replace("@@" + _k + "@@", str(_v))
leftover = re.findall(r"@@\w+@@", TEX)
assert not leftover, leftover

open(OUT, "w", encoding="utf-8").write(TEX)
print("wrote", OUT, f"({len(TEX)} chars)")
print()
print(SUBS["PIVOTROWS"])
print()
print(SUBS["SPEEDROWS"])
