"""Generated supplement sections (supplement/sec_r14.tex) and the verbatim outputs they include (supplement/data/),
from the saved outcomes in the code repository (research/r7c/r14, r12) and the manuscript's generated macros.
Usage: python make_supp_sections.py   (run with the repository .venv)"""
import json, os, re, shutil
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..", "02_paper_repo_inarcp", "research", "r7c")
if not os.path.isdir(REPO):
    REPO = r"C:\Users\DELL\Downloads\MS thess\02_paper_repo_inarcp\research\r7c"
SUP = os.path.join(HERE, "..", "supplement"); MAN = os.path.join(HERE, "..", "manuscript")
S = json.load(open(os.path.join(REPO, "r14", "r14_summary.json")))
MAC = {}
for f in os.listdir(os.path.join(MAN, "generated")):
    if f.endswith("_macros.tex"):
        for k, v in re.findall(r"\\newcommand\{\\(\w+)\}\{([^}]*)\}", open(os.path.join(MAN, "generated", f), encoding="utf8").read()):
            MAC[k] = v
sha14 = open(os.path.join(REPO, "r14", "PROTOCOL_R14.sha256")).read().split()[0]
import textwrap
for src, dst in (("r14/r14_summary.txt", "r14_summary.txt"), ("r14/theory_check_independent_output.txt", "theory_check_independent_output.txt")):
    lines = open(os.path.join(REPO, src), encoding="utf8").read().splitlines()   # wrap only lines too long for the page
    out = [w for ln in lines for w in (textwrap.wrap(ln, 175, subsequent_indent="      ", drop_whitespace=False) if len(ln) > 175 else [ln])]
    open(os.path.join(SUP, "data", dst), "w", encoding="utf8").write("\n".join(out) + "\n")
shutil.copy(os.path.join(MAN, "generated", "tab_target.tex"), os.path.join(SUP, "tab_target.tex"))

f2 = lambda x: f"{x:.2f}"
g3 = lambda g: S[f"G|scr50look0|random|{g}"] - S["G|scr50look0|random|0"]
row = lambda name, cond: S[f"{cond}|0.01|{name}"]
tl = {(round(p, 3), a, int(b)): int(t) for p, a, b, t in S["trim_levels"]}
cost = lambda name, p: row(name, f"bern|{p}|30")["cost"]
t2, t5 = tl[(0.02, 0.01, 0)], tl[(0.05, 0.01, 0)]

tex = rf"""% Generated by analysis_provenance/make_supp_sections.py from the saved outcomes. Do not edit.
\section{{Guarded scale, clip level, certified trimming, pulse blanking and bursts (R14)}}\label{{sup:r14}}
Frozen protocol \texttt{{r14/PROTOCOL\_R14.md}} (sha256 {sha14[:8]}\ldots), written after a synthetic dry run and before any IPIX outcome; expectations and verdicts in \texttt{{r14/RESULTS\_R14.md}} (12 of 15 met). The settings are those of the final IPIX study, except for dense calibration: non-overlapping 24-pulse segments, about {MAC['DwellSegsPerUnit']} per unit, so that $\alpha=10^{{-3}}$ is resolved. The study tested five changes:
\begin{{itemize}}
\item a guard of $\Delta\in\{{0,8,16\}}$ pulses between the scale window and the tested pulse;
\item clip levels $\kappa\in\{{4,6,9,12,18\}}$;
\item a certified trimmed sum, which discards the largest dwell terms; the number discarded is the smallest for which more corrupted dwell innovations than discarded terms have probability at most $\alpha/5$ under the hit model ({t2} of eight at a 2\% and {t5} at a 5\% hit rate at $\alpha=10^{{-2}}$; no such number exists for bursts);
\item pulse blanking of isolated spikes, calibrated with masks drawn from the hit model and passed through the same rule (mask-matched calibration);
\item bursts of eight consecutive pulses at the same mean hit rate.
\end{{itemize}}
The certified thresholds use the worst case of Theorem~\ref{{M-thm:cert}} with hits drawn either from the independent-hit model or from the burst model. The guard leaves the false-alarm law unchanged; the measured $P_{{\rm fa}}/\alpha$ with $\Delta=8$ is {f2(S['G|pfa|8|0.01'][0])} at $10^{{-2}}$ and {f2(S['G|pfa|8|0.001'][0])} at $10^{{-3}}$. The real IPIX target stays undetected with every guard (exceedance {S['G|target|8|0.001']:.4f} at $10^{{-3}}$ with $\Delta=8$), because it is present in every history.

\emph{{Unmet expectations of R14.}}
\begin{{itemize}}
\item \textbf{{Onset cost (G3).}} The guard was expected to cost at most 0.5~dB at onset. It costs {g3(8):.1f}~dB with $\Delta=8$ and {g3(16):.1f}~dB with $\Delta=16$, because the scale is older.
\item \textbf{{Certification at $10^{{-3}}$ (K2).}} The certificate at the clip level chosen by the saturation rule was expected to reach $P_{{\rm d}}=0.5$ below 25~dB in all four interference conditions at $10^{{-3}}$. With 5\% hits the certificate is vacuous at $10^{{-3}}$ for every clip level.
\item \textbf{{Cost of trimming (T2).}} Trimming was expected to cost more than clipping at both hit rates. At 5\% it costs {cost(f'cert(bern) trim t={t5}', 0.05):+.1f}~dB against {cost('cert(bern) clip6', 0.05):+.1f}~dB for clipping ($\kappa=6$).
\end{{itemize}}
The SCR for $P_{{\rm d}}=0.5$ is fragile under 5\% hits, because the certified detection curve is nearly flat there, so the main text reports $P_{{\rm d}}$ at 10~dB.

\noindent Output of \texttt{{r14/analyze\_r14.py}}. Columns of the interference table: condition, $\alpha$, statistic, pooled $P_{{\rm fa}}/\alpha$ [upper day-cluster bound], SCR for $P_{{\rm d}}=0.5$, its cost against clean clipping ($\kappa=6$), and $P_{{\rm d}}$ at 10 and 25~dB.
\dataverb{{r14_summary}}

\section{{Independent re-check of the main laws and of Theorem~\ref{{M-thm:cert}}}}\label{{sup:indep}}
\texttt{{r14/theory\_check\_independent.py}} re-derives the main closed forms of Section~\ref{{M-sec:laws}} and Theorem~\ref{{M-thm:cert}} by Monte Carlo on a GPU (the remaining laws are checked by the study scripts, Section~\ref{{sup:r12}}). It was written from scratch and does not import the code that implements the laws. It checks:
\begin{{itemize}}
\item Proposition~\ref{{M-prop:law}}, including repeated eigenvalues and a singular $Q$;
\item Proposition~\ref{{M-prop:rank1}};
\item the horizon of Corollary~\ref{{M-cor:horizon}};
\item the strong-target OS law \eqref{{M-eq:osstrong}}, the integration laws and the known-bin P-ANMF law;
\item the Beta law (by Monte Carlo) and the calibration sizes (by exact computation);
\item Theorem~\ref{{M-thm:cert}} under strong, matched and cancelling interference.
\end{{itemize}}
It also includes a misspecified case: bursts against a certificate calibrated on independent hits, which violates the dominance condition. There the clipped certificate exceeds $\alpha$, as the theorem's condition implies it may.
\dataverb{{theory_check_independent_output}}
\noindent The guarded post-onset law (Proposition~\ref{{M-prop:rank1}} with $\ell$ replaced by $\ell-\Delta$) is checked separately by \texttt{{r14/theory\_check\_guard.py}}, also written from scratch. With $\Delta=8$ the decay is that of $\Delta=0$ delayed by eight looks:
\dataverb{{theory_check_guard}}
\noindent The line for $n=23{{,}}000$ checks the formula only. The low-false-alarm calibration sets have {MAC['LowCalMin']}--{MAC['LowCalMax']} episodes per unit, for which the same formula gives $\PP\{{P_{{\rm fa}}>2\alpha\}}={MAC['LowCalPtwoMin']}$--{MAC['LowCalPtwoMax']} (Section~\ref{{M-sec:calib}}).

\section{{The real IPIX target: detection versus dwell length}}\label{{sup:target}}
\begin{{table}}[h]
\centering\small
\caption{{Real IPIX target (primary cell, test thirds, 56 units): mean $P_{{\rm d}}$ at design $P_{{\rm fa}}=10^{{-3}}$ versus dwell $N$. In parentheses: measured clutter $P_{{\rm fa}}$ ($\times10^{{-3}}$). P-ANMF with Fisher's $g$ uses the analytic threshold.}}
\label{{tab:target}}
\input{{tab_target.tex}}
\end{{table}}
Calibration of the self-normalized detector degrades for longer, overlapping windows. Its analytic Fisher's $g$ threshold fails already at $N=8$, consistent with imperfect whitening by an AR(4) model fitted on neighboring cells. The value of P-ANMF here is a calibrated short-dwell threshold, not sensitivity.

\section{{77~GHz data: receivers, range bins and thermal noise}}\label{{sup:jkusel}}
Range bins 8--247 of receivers 0, 5, 10 and 15 of both stations are used. As the CNR rises from noise-dominated cells to 10--20~dB, the measured gain of IN-ARCP over local power detection rises from ${MAC['JINGainLow']}$~dB to ${MAC['JINGainHigh']}$~dB, following the sign of Proposition~\ref{{M-prop:gain}}.

\section{{Further detector notes}}\label{{sup:notes}}
\begin{{itemize}}
\item \textbf{{Power-detector laws.}} At $10^{{-3}}$ the white-noise laws of the power detectors err in both directions: CA16 runs at {MAC['LCaWhiteThree']} times design and the OS detector on raw powers at {MAC['LOsRawThree']} times design.
\item \textbf{{OS variants after onset.}} The OS variants with $k=12$ and with AR(4) innovations collapse at the first look at which the target occupies more than $m-k$ history innovations, as \eqref{{M-eq:osstrong}} states. The pre-specified count was off by one and was corrected after the data were seen (Section~\ref{{sup:deviations}}).
\item \textbf{{Worst case in Theorem~\ref{{M-thm:cert}}.}} The worst case over amplitudes is attained for the clipped dwell terms, which strong interference drives to $\kappa$. It is conservative only through the history scale, whose corrupted entries are set to zero.
\item \textbf{{Certified binary integration.}} In the final IPIX study (R12, sparse calibration), the detection probability of certified binary integration for a 10~dB target was within {MAC['BinCertGapMax']} of that of certified clipping at both hit rates and powers (output in Section~\ref{{sup:r12}}).
\end{{itemize}}
"""
open(os.path.join(SUP, "sec_r14.tex"), "w", encoding="utf8").write(tex)
print("sec_r14.tex written;", len(tex), "chars")

# ------------------------------------------------------------------ R15: NetRAD
N = json.load(open(os.path.join(REPO, "r15", "r15_summary.json")))
sha15 = open(os.path.join(REPO, "r15", "PROTOCOL_R15.sha256")).read().split()[0]
for src, dst in (("r15/r15_summary.txt", "r15_summary.txt"), ("r15/explore_r15_hotspots_output.txt", "r15_hotspots.txt"),
                 ("r15/explore_r15_attribution_output.txt", "r15_attribution.txt"), ("r14/theory_check_guard_output.txt", "theory_check_guard.txt"),
                 ("r15/explore_r15_flag_extent_output.txt", "r15_flag_extent.txt")):
    lines = open(os.path.join(REPO, src), encoding="utf8").read().splitlines()
    out = [w for ln in lines for w in (textwrap.wrap(ln, 175, subsequent_indent="      ", drop_whitespace=False) if len(ln) > 175 else [ln])]
    open(os.path.join(SUP, "data", dst), "w", encoding="utf8").write("\n".join(out) + "\n")
V = N["verdicts"]
L15 = N["L"]
out4 = [k.split("|")[0] for k in L15 if k.endswith("|conf|0.0001") and not (0.5 <= L15[k][0] <= 2)]
OUT4 = ", ".join(f"{k} ({L15[k + '|conf|0.0001'][0]:.2f})" for k in out4).replace("_", "\\_")
tex15 = rf"""% Generated by analysis_provenance/make_supp_sections.py from the saved outcomes. Do not edit.
\section{{Second sea-clutter radar: NetRAD (R15)}}\label{{sup:r15}}
Frozen protocol \texttt{{r15/PROTOCOL\_R15.md}} (sha256 {sha15[:8]}\ldots). It was written before any statistic of the NetRAD samples was computed. Before that point only the following had been read: file sizes, array shapes, and the providers' scripts and log. In addition, two of the providers' own quick-look images were viewed while the dataset was being located. Expectations and verdicts are in \texttt{{r15/RESULTS\_R15.md}} ({MAC['NetMet']} of {MAC['NetExp']} met), and deviations in \texttt{{r15/DEVIATIONS\_R15.md}}. The deviations are a corrected site description (the Atlantic side of the Cape Peninsula, not False Bay) and run mechanics; none changes a method, setting or expectation.

\emph{{Data.}} Node 3 (monostatic) of the NetRAD system: seven HH and seven VV recordings of 130{{,}}000 pulses at 1~kHz. The clutter cells are the providers' per-recording range windows (\texttt{{NR\_Range\_Selection\_June9.m}}). Each cell has its complex mean removed and is scaled to unit power. The cross-polarized recordings were set aside before any data were read. All methods are the frozen R12 and R14 code. The only change is that the ANMF secondary cells are restricted to those two to four cells away, which gives 15--30 vectors (20--35 on IPIX). The AR(1) clamp $|r|\le0.98$ binds in 12 of the 14 recordings.

\emph{{Unmet expectations of R15.}}
\begin{{itemize}}
\item \textbf{{Calibration at $10^{{-4}}$ (N1).}} At least 12 of 13 conformal ratios were expected within $[0.5,2]$ at $10^{{-4}}$; {13 - len(out4)} were. Outside: {OUT4}. At $10^{{-3}}$ all 13 are within $[0.5,2]$, and the 12 non-saturating statistics lie within {MAC['NetConfMinThree']}--{MAC['NetConfMaxThree']} times design.
\item \textbf{{Pivotality ranking (N4).}} IN-ARCP's quintile spread at $10^{{-2}}$ was expected to be at most 2 and below CA16's. It is {MAC['NetSpreadIn']} against {MAC['NetSpreadCa']}. In the same analysis on IPIX it is {MAC['NetSpreadInIpix']} against {MAC['NetSpreadCaIpix']}, so this expectation had no support on IPIX either.
\item \textbf{{Flagged pulses (W2).}} Non-coherent integration with a clean threshold was expected to exceed $1.5\alpha$ in segments with flagged pulses. It stays at {MAC['NetWDinHit']} times design.
\end{{itemize}}
Expectation N5 (PAMF-H within 0.5~dB of the best dwell detector) was met, but it is uninformative: every whitened dwell detector reaches $P_{{\rm d}}=0.5$ at the lowest SCR tested.

\emph{{Exploratory (post hoc, after the outcomes and the claim audit).}} Two scripts look at where the conformal exceedances at $10^{{-4}}$ fall: \texttt{{r15/explore\_r15\_hotspots.py}} and \texttt{{r15/explore\_r15\_attribution.py}}.
\begin{{itemize}}
\item \textbf{{Integration and PAMF-H.}} Most of their excess comes from two VV units (1450 and 1501, assignment 3). Their exceedances fall within one to three seconds of the test third and coincide with flagged pulses, while their calibration thirds contain no flagged pulse. Without these two units the pooled ratios are {MAC['NetAttrDin']} (integration) and {MAC['NetAttrPamf']} (PAMF-H).
\item \textbf{{P-ANMF statistics.}} Their excess comes from one HH unit (1128, assignment 3) with frequent flagged pulses in both thirds. Fewer than half of its exceedances coincide with flagged pulses.
\item \textbf{{Unexplained.}} The flagged pulses do not explain the excess of the noise-aware score ({MAC['NetNaFour']}). Nor do they explain an excess of integration of more than five times design in one unit that has no flagged pulse at all (1508, assignment 2).
\end{{itemize}}
\textbf{{What the flags are is not established.}} \texttt{{r15/explore\_r15\_flag\_extent.py}} counts, in the raw recordings, the range bins above ten times their median:
\begin{{itemize}}
\item a flagged HH pulse has a median of about 108 such bins, of 1024, and 85--91\% of them lie outside the clutter window;
\item unflagged HH pulses with an elevated window bin have about 80.
\end{{itemize}}
The flags are therefore the upper tail of a phenomenon that extends over range. They may be wideband interference: the providers remove WiFi pulses in their own processing of the bistatic nodes. They may equally be range-extended HH sea spikes. The main text therefore calls them flagged pulses, not interference.

In the clutter cells, uncertified non-coherent integration runs at {MAC['NetWDin']} times design at $10^{{-2}}$ and {MAC['NetWDinThree']} at $10^{{-3}}$ over all test segments of the {MAC['NetWElig']} HH recordings, the only ones with at least 0.5\% flagged pulses (VV: at most {MAC['NetHitVVMax']}\%). Segments without a flagged pulse give {MAC['NetWDinNone']} and {MAC['NetWDinNoneThree']}; segments with flagged pulses give at most {MAC['NetWDinFlagMax']} and {MAC['NetWDinFlagMaxThree']}, with wide intervals at $10^{{-3}}$ (Part W below). A certificate whose hit model must cover these frequent, bursty masks is nearly vacuous ($P_{{\rm d}}={MAC['NetWCertPd']}$). Blanking with mask-matched calibration keeps $P_{{\rm d}}={MAC['NetWBlankPd']}$ at {MAC['NetWBlank']} times design.

\noindent Output of \texttt{{r15/analyze\_r15.py}} (Parts L, A, G, I, K/X/B and W; intervals resample recordings):
\dataverb{{r15_summary}}
\noindent Exploratory hotspot analysis (\texttt{{r15/explore\_r15\_hotspots.py}}):
\dataverb{{r15_hotspots}}
\noindent Exploratory attribution (\texttt{{r15/explore\_r15\_attribution.py}}): flagged-pulse fraction in each unit's calibration and test thirds, the per-unit ratios at $10^{{-4}}$, and the pooled ratios without the units named above:
\dataverb{{r15_attribution}}
\noindent Exploratory range extent of the flagged pulses (\texttt{{r15/explore\_r15\_flag\_extent.py}}):
\dataverb{{r15_flag_extent}}
"""
open(os.path.join(SUP, "sec_r15.tex"), "w", encoding="utf8").write(tex15)
print("sec_r15.tex written;", len(tex15), "chars")

# ------------------------------------------------------------------ dwell table (moved from the main text in R15)
shutil.copy(os.path.join(MAN, "generated", "tab_dwell.tex"), os.path.join(SUP, "tab_dwell.tex"))
shutil.copy(os.path.join(MAN, "figures", "fig_theory.pdf"), os.path.join(SUP, "fig_theory_full.pdf"))
texd = r"""% Generated by analysis_provenance/make_supp_sections.py. Do not edit.
\section{Closed forms against Monte Carlo: all six panels}\label{sup:theoryfig}
\begin{figure}[h]
\centering\includegraphics[width=.95\textwidth]{fig_theory_full.pdf}
\caption{Closed forms (lines) against Monte Carlo (markers; $10^5$ episodes per point in (a), (c) and (f), $5\times10^4$ in (b) and (d), $10^4$ to $2.5\times10^4$ in (e)) at the true coefficient, AR(1) compound-Gaussian clutter with $\rho=0.93e^{-0.2\mathrm j}$, lognormal texture, $m=16$, $P_{\rm fa}=0.01$. Panels (a)--(c) and (f) are those of Fig.~\ref{M-fig:theory} of the paper, where (f) appears as its panel (d) and (c) here adds the RMS-scale law for reference. The two panels shown only here are (d), the integration law \eqref{M-eq:dwellpd}, and (e), P-ANMF with unknown Doppler. JNR in (f): interference-to-clutter-plus-noise power ratio.}
\end{figure}

\section{Dwell detection on IPIX}\label{sup:dwell}
\begin{table}[h]
\centering\small
\caption{SCR (dB) for $P_{\rm d}=0.5$ and $0.9$ over an 8-pulse dwell: persistent Swerling-1 target with random Doppler from the first dwell pulse (IPIX, conformal thresholds). $\le-5$: reached at the lowest SCR tested; n.r.: not reached at 25~dB.}
\label{tab:dwellsup}
\input{tab_dwell.tex}
\end{table}
"""
open(os.path.join(SUP, "sec_dwell.tex"), "w", encoding="utf8").write(texd)
print("sec_dwell.tex written")

