"""Size every verbatim result dump in the supplement as large as it will fit.

R18 float audit: 108,786 of the supplement's characters were set at 5 pt — the `\\tiny` of
every `\\VerbatimInput` — which is the bulk of the document and is hard to read. The 5 pt
choice was uniform, but the dumps are not: their longest lines run from 82 to 175 characters,
so most of them had room to be much larger.

Measured on the built supplement (letterpaper, 1.5 cm margins): the text block is 527 pt wide
and a monospace character at 5 pt is 2.645 pt, so 996/s characters fit at size s. This script
gives each file the largest size that still fits its own longest line, with a 3% safety margin,
capped at 8 pt so the dumps do not compete with the 10 pt prose.

It writes `supplement/verbatim_sizes.tex`, which defines one `\\dataverb{<stem>}` per file.
`supplement.tex` and the generated sections call `\\dataverb{...}` instead of
`\\VerbatimInput[fontsize=\\tiny]{...}`.

Run from 03_submission_IEEE-TRS/:   python analysis_provenance/make_supp_verbatim.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DATA = os.path.join(PKG, "supplement", "data")
OUT = os.path.join(PKG, "supplement", "verbatim_sizes.tex")

TEXT_WIDTH_PT = 527.0       # measured from the built supplement
CHAR_W_AT_5PT = 2.645       # measured from the built supplement
CHARS_AT_1PT = TEXT_WIDTH_PT / (CHAR_W_AT_5PT / 5.0)   # = 996
SAFETY = 0.93
FLOOR, CEIL = 5.0, 8.0

rows = []
for f in sorted(os.listdir(DATA)):
    if not f.endswith(".txt"):
        continue
    stem = f[:-4]
    with open(os.path.join(DATA, f), encoding="utf-8", errors="replace") as fh:
        longest = max((len(line.rstrip("\n")) for line in fh), default=1)
    size = CHARS_AT_1PT * SAFETY / max(longest, 1)
    size = max(FLOOR, min(CEIL, size))
    size = int(size * 10) / 10.0          # round down to 0.1 pt
    rows.append((stem, longest, size))

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(
        "% Generated by analysis_provenance/make_supp_verbatim.py. Do not edit.\n"
        "% One size per result dump: the largest that fits that file's longest line in the\n"
        "% 527 pt text block, with a 3% margin, capped at 8 pt. Longest lines, in characters,\n"
        "% are in the comments. Use \\dataverb{<stem>} to include data/<stem>.txt.\n"
        "\\makeatletter\n"
    )
    for stem, longest, size in rows:
        # the key is the stem exactly; \csname tolerates the underscores
        fh.write(
            f"\\expandafter\\def\\csname vbsz@{stem}\\endcsname{{{size:.1f}}}"
            f"% {longest} chars\n"
        )
    fh.write(
        "\\newcommand{\\dataverb}[1]{%\n"
        "  \\@ifundefined{vbsz@#1}{\\def\\@vbsz{5.0}}"
        "{\\edef\\@vbsz{\\csname vbsz@#1\\endcsname}}%\n"
        "  \\dimen@=\\@vbsz pt\\relax \\dimen@=1.2\\dimen@\n"
        "  \\VerbatimInput[fontsize={\\fontsize{\\@vbsz pt}{\\the\\dimen@}\\selectfont}]"
        "{data/#1.txt}}\n"
        "\\makeatother\n"
    )

print("wrote", OUT)
print(f"{'file':<40} {'longest':>8} {'pt':>6}")
for stem, longest, size in rows:
    print(f"  {stem:<38} {longest:>8} {size:>6.1f}")
big = sum(1 for _, _, s in rows if s > 5.0)
print(f"\n{big} of {len(rows)} dumps can be larger than 5 pt; "
      f"mean size {sum(s for _, _, s in rows)/len(rows):.1f} pt")
